version: 0.2
 
env:
  variables:
    PROJECT_NAME: "CodeBuild-Synopsys-Detect"
  parameter-store:
    BLACKDUCK_URL: "detect-BD-URL"
    BLACKDUCK_TOKEN: "detect-BD-Token"
 
phases:
  install:
    commands:
      - curl -LOk https://detect.synopsys.com/detect8.sh
      - chmod +x ./detect8.sh
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - bash detect8.sh --blackduck.url=$BLACKDUCK_URL --blackduck.api.token=$BLACKDUCK_TOKEN --blackduck.trust.cert=true --detect.project.name=$PROJECT_NAME --detect.project.version.name=$CODEBUILD_BUILD_ID --detect.accuracy.required=NONE
      - curl -X POST https://testing.codedx.synopsys.com/codedx/api/analysis-prep/ASMB/analyze -H "accept: */*" -d
  
artifacts:
  discard-paths: yes
